### ISSUE TITLE
NoSuchMethodError while deserializing YAML

### ISSUE THREAD

**Issue by Iltotore** [circe/circe#1559]
Hello,
I'm trying to deserialize my YAML file into case class using automatic derivation but I receive a [NoSuchMethodError](https://hasteb.in/kofuyase) during initialization.

Code called:
```scala
val info = (try parse(configSource.mkString).flatMap(_.as[UHCInfo]) finally configSource.close()) match {
  case Right(value) => value

  case Left(exception) => throw exception.fillInStackTrace()
}
```

Decoders:
```scala
  //Sponge decoders
  implicit val Vector3dDecoder: Decoder[Vector3d] = Decoder.instance(cursor => cursor.value.fields("x", "y", "z") match {
    case Seq(jsonNumber(x), jsonNumber(y), jsonNumber(z)) => Right(new Vector3d(x.toDouble, y.toDouble, z.toDouble))

    case _ => Left(DecodingFailure("Vector3d expected", List.empty))
  })

  implicit val ItemStackDecoder: Decoder[ItemStack] = Decoder.instance(cursor => cursor.value.fields("typeId", "amount") match {
    case Seq(jsonString(typeId), jsonInt(amount)) =>
      Sponge.getRegistry.getType(classOf[ItemType], typeId)
        .map(ItemStack.of(_, amount))
        .toScala
        .toEither(DecodingFailure("ItemStack expected", List.empty))

    case _ => Left(DecodingFailure("ItemStack expected", List.empty))
  })

  implicit val World: Decoder[World] = Decoder.instance(cursor =>
    Sponge.getServer.getWorld(cursor.value.asString.get)
      .toScala
      .toEither(DecodingFailure("World expected", List.empty))
  )

  //Config decoders
  implicit val AreaDecoder: Decoder[Area] = deriveDecoder //Error
  implicit val DropDecoder: Decoder[Drop] = deriveDecoder
  implicit val ExperienceDecoder: Decoder[ExperienceInfo] = deriveDecoder
  implicit val UHCDecoder: Decoder[UHCInfo] = deriveDecoder
```
Each type used in these case classes has an implicit Decoder.
**Note: I'm raising this issue here because it's about different circe libs (generics, yaml etc...)**

Edit: here is the YAML:
```yml
baseArea:
  world: world
  start:
    x: 0
    y: 0
    z: 0
  end:
    x: 0
    y: 0
    z: 0
endArea:
  world: world
  start:
    x: 0
    y: 0
    z: 0
  end:
    x: 0
    y: 0
    z: 0
deathDrops: []
invulnerability: 100
```
